### PR TITLE
Add Anagram

### PR DESCRIPTION
**Pull request by s0kil**

### CODE REVIEW

**Comment by s0kil** [comment]
Not sure why we have an merge conflict...

**Comment by s0kil** [comment]
It seems I tried to format the README table, and then you reverted the changes.

**Comment by s0kil** [comment]
The README Table is very hard to work with on different screen sizes.

**Comment by RamseyNjire** [comment]
No, kept your format as is but changed the order to alphabetical. I thought it might be easier to skim the challenge table as it scales that way.

**Comment by s0kil** [comment]
Replaced By: https://github.com/RamseyNjire/coding-challenges-solved-and-explained/pull/7

**Pull request closed without merging**
